window.onload = function () {
    hit = false,
    i = 0,
    buttons = [],
    charCodeA = 65,
    charCodeZ = 90,
    disableInput = false,
    buttonContainer = document.getElementById('buttons'),
    livesContainer = document.getElementById('lives'),
    wordContainer = document.getElementById('word'),
    nextButton = document.getElementById('next');
    words = ["TITANIC", "SCHIFFAHRTSGESELLSCHAFT", "COMPUTERABSTURZ", "VORSTANDSSPRECHER", "MAGAZIN", "ZUFALL", "CYBERSEX", "KONTAKTANZEIGEN", "KOSTENPFLICHTIG", "KREDITKARTE", "EISENBAHN", "WIRRUNGEN", "FAMILIENLEBEN", "ATLANTIK", "TYPENVIELFALT", "ZUGBEGLEITERINNEN", "HOCHSOMMERTAG", "KRATZER", "ARBEITSINSTRUMENT", "SERVERSTEUERUNG", "AUSBLICK", "NASENSCHLEIM", "GANGSCHALTUNG", "OPFER", "REIS", "ESSSTAEBCHEN", "LIEGESTUHL", "WASSERMELONE", "STROHHALM", "LAWINE", "WEINTRAUBE", "DATENVERARBEITUNG", "PORZELLAN", "AKTIE", "QUALLE", "KORREKTUR", "MARATHONLAUF", "PFERDERENNEN", "ORCHESTER", "NATURKATASTROPHE", "ZINSSATZ", "ADVENT", "KAPITAL", "POST", "DATENBANK", "NETZWERKUMGEBUNG", "ZWISCHENZEIT", "PFANNE", "MAUSTASTE", "HANDBUCH", "ZUSAMMENSETZUNG", "SHANGHAI", "CHINA", "VITAMINE", "MAUS", "FEUERWEHR", "FUSSBALL", "STRASSENLATERNE", "PROTOKOLL", "ELECTRONIC", "LOKOMOTIVE", "BASEL", "SCHWEIZ", "KALENDER", "DRUCKER", "AUTOBAHN", "BANGKOK", "TELEFON", "KREDITOR", "BEARBEITUNG", "ZYLINDERROLLENLAGER", "SEGELFLUGZEUG", "MOTORFLUGZEUG", "FEUER", "ANANAS", "HANGMAN", "HALLO", "WEISSWEIN", "OBERAFFENGEIL", "SCHLAGERFORUM", "KILOMETER", "WURSTSALAT", "WANDERGESELLE", "NASHORNAUGEN", "UNIKAT", "WORT", "POLIZEI", "SCHWARZMARKT", "PENISOPERATION", "TAKTFREQUENZ", "LOEFFEL", "MAISKOLBEN", "MAUSZEIGER", "UNSINN", "KIPPE", "DRUCKERANSCHLUS", "BIER", "BIERFASS", "FAHRRADSATTELTASCHE", "BUNDESRAT", "TATSACHE", "PUSTEKUCHEN", "KIRSCHKERNWEITSPUCKWETTBEWERB", "KOSTENVORANSCHLAG", "PILLERMANN", "ARSCHGESICHT", "COMPUTERDATENBANKZUSATZSPEICHER", "DANKE", "SPREEWALD", "KINGSWAY", "EPSONDRUCKER", "CHILICHIPS", "SENTABABY", "HANDYGAME", "HUEHNERSUPPE", "ROCKY", "EISTEE", "OBERAFFENMEGAGEIL", "SCHWANGERSCHAFTSKONFLIKTBERATUNG", "KIRCHENOBERHAUPT", "RABE", "BOFU", "PARANOID", "SCHWEINFURT", "PAPPPLAKATKLEBER", "MORGENMUFFEL", "SCHLAFWANDLER", "BLIND", "EGAL", "DONAUDAMPFSCHIFFFAHRTGESELLSCHAFTSKAPITAENMUETZE", "LOOSER", "YANKEE", "SCHILLERSTRASSE", "SYNAPSE", "KLEISTER", "FLUGZEUGGESCHWADER", "FRAGESTUNDE", "ALPHUETTENKAESE", "MALERBETRIEB", "ARZTHELFER", "GLUECK", "BALLERMANN", "PFERD", "NAME", "KLEINLAUT", "KNOCHEN", "BRECHEN", "LACHEN", "ENTSCHEIDUNG", "ZEPPELIN", "BALLON", "HORIZONT", "FRECHDAX", "GESCHLECHTSVERKEHR", "LIEBE", "GEBORGENHEIT", "REDEN", "HAUS", "BAUMSTAMM", "ROTZNASE", "WEIHNACHTSGESCHENK", "KAFFEEMASCHINE", "KAFFEESAHNE", "AQUARIUM", "AUTOSCHIEBERBANDE", "WECHSELGELD", "KELLNER", "LIEBESBOTE", "WOERTERBUCH", "KLAGENFURT", "YACHT", "ZEBRA", "TANZENBERG", "THOMAS", "COLUMBO", "CHER", "ENYA", "AUTOBUS", "OMNIBUS", "KOFFERRAUM", "EINTAUSENDSECHSHUNDERTNEUNUNDFUENFZIG", "STADTHALLE", "RAHMSCHNITZEL", "KAERNTEN", "TIROL", "VORARLBERG", "WIEN", "BURGENLAND", "NIEDEROESTERREICH", "OBEROESTERREICH", "SALZBURG", "MIKRONESIEN", "VADUZ", "LIECHTENSTEIN", "ITALIEN", "AEQUATORIALGUINEA", "FLUGZEUGABSTURZ", "MARIANENGRABEN", "PAPST", "PAPYRUS", "BRITNEY", "QUENTIN", "QUATAR", "QUEBEC", "TATU", "KATZENKLO", "FRESSNAPF", "HOFER", "BILLA", "ZIELPUNKT", "OESTERREICH", "FEHLER", "MATHEMATIK", "OEKOLOGIE", "MORD", "WUNDER", "WASCHMITTEL", "BODEN", "FLIESE", "ROM", "UBAHN", "STRASSENBAHN", "REIFENPANNENDREIECK", "COMPUTERSPIEL", "MITTERNACHT", "GOLDFISCH", "HUNDERASSE", "HAMSTER", "KIWI", "LINDSAY", "BADVORLEGERTEPPICH", "TUTENCHAMUN", "TAKTFREQUENZ", "SHAKIRA", "TOMATENSUGO", "ZIGEUNERSCHNITZEL", "PAPRIKA", "BROMBEERE", "SCHIMMEL", "KASTEN", "KIKA", "LUTZ", "SCHLECKER", "STADTWERKE", "STADTWERKEBUS", "JUGO", "PIFKE", "GURKE", "OBSTSALAT", "BODENFLIESE", "VORHANG", "VORHANGSTANGE", "SPUELMITTEL", "WAESCHETROCKNER", "LATEIN", "DEUTSCH", "ITALIENSICH", "ENGLISCH", "WERKEN", "ZEICHNEN", "TURNEN", "BIOLOGIE", "CHEMIE", "PHYSIK", "GEOGRAFIE", "RELIGION", "PSYCHOLGIE", "IRINA", "PETER", "SABINE", "JOSEFA", "ELFRIEDE", "PAULA", "GERLINDE", "HENDL", "SCHNITZEL", "STEPHANSDOM", "LINDWURM", "NATTER", "SCHWANENSEE", "MARGE", "HOMER", "BART", "LISA", "MAGGIE", "SIMOR", "SIMON", "ALPHABET", "ZEITUNGSAUSTRAEGER", "KASERNE", "BUNDESHEER", "PULLOVER", "JEANS", "HANDTUCH", "EXISTIERT", "BEREITS", "BITTE", "RUSSLAND", "DAENEMARK", "ZYPERN", "THANKS", "WEIHNACHTEN", "GRAZ", "INNSBRUCK", "DORNBIRN", "BREGENZ", "EISENSTADT", "LINZ", "STUR", "HUMMEL", "BIENE", "SEESTERN", "MUSCHEL", "SAND", "SANDSTRAND", "SANDBAR", "KILOGRAMM", "STAUBFUSSEL", "KIRCHENCHORGESANGSKAPELLENRAUMVORHANGSTANGE", "MEDUSA", "PERSEUS", "ANDROMEDA", "XANTHIPPE", "XAVER", "XENA", "XYLOPHON", "XANTEN", "XCHROMOSOM", "YEN", "YVONNE", "JAPAN", "AMERIKA", "EUROPA", "ASIEN", "AUSTRALIEN", "AFRIKA", "LEXIKON", "CAESAR", "CLEOPATRA", "CICERO", "HORAZ", "VERGIL", "PLINIUS", "TACITUS", "SOKRATES", "ZENON", "MAROKKO", "AEGYPTEN", "TSCHIBUTI", "OMAN", "NIEDERLANDE", "BRASILIEN", "NICARAGUA", "PASCAL", "AIRBUS", "WACHSEN", "LESEN", "DENKEN", "MUEDE", "QUER", "QUENDULA", "QUINTIUS", "QUIRIN", "HITRADIO", "BUEHNE", "TISCHDECKE", "DECKERL", "ESPANOL", "BACKFORM", "UNKRAUT", "ANASTACIA", "TEPPICH", "PANTER", "OKTOBER", "UMGEBUNG", "ASCHENBECHER", "ZIGARETTEN", "KATZENKOERBCHEN", "FENSTER", "BUSSTAND", "WINTER", "SONNENSCHEIN", "ARSCH", "LIEBLING", "SCHATZ", "ENGEL", "DISKUSION", "RESIGNATION", "GUANIN", "ADEMIN", "THYMIN", "CYTOSIN", "KUHEUTER", "COMPUTER", "ADMINISTRATOR", "ZWERG", "DUSCHVORHANG", "DOOM", "ZORRO", "STANDESAMT", "KINDERWAGEN", "AUTO", "ENTE", "TOILETTENBRILLE", "WOLFSBURG", "SERVER", "HINZUFUEGEN", "EXISTIEREN", "ANZAHL", "STERN", "STERNCHEN", "ANSCHLAG", "STABHOCHSPRINGER", "HAMMER", "VOGEL", "SCHRAUBE", "DATTELPALME", "DONAUDAMPFSCHIFFFAHRTSKAPITAENSMUETZENBLAU", "IPHIGENIE", "TAURIS", "LESSING", "BISMARCK", "FORMOSA", "INDOCHINA", "PARTITUR", "SCHOLL", "ROSE", "HOSE", "ALSBALD", "MEHRMALS", "DORT", "HIER", "MEHR", "KLEIN", "DELUXE", "MONARCHIE", "PENTARCHIE", "ALLIANZ", "DINGE", "APFELSAFTSCHORLE", "FACHARBEITSBESPRECHUNGSTERMIN", "NACH", "FACHARBEITSGLIEDERUNGSBLATT", "FACHARBEITSGLIEDERUNG", "NOTEBOOK", "BRIEFUMSCHLAG", "HANDY", "TASCHENTUCH", "GEOLOGE", "BRIEF", "BERG", "KARTON", "VITAMIN", "MAGNESIUM", "CALCIUM", "PAPIER", "STIFT", "GELD", "STEUERBERATER", "RECHTSANWALT", "KABEL", "WEIHNACHTSBAUM", "CHRISTBAUMKUGEL", "LICHTERKETTE", "LAMPE", "LEUCHTE", "GUMMIBAND", "SCHRANK", "MARTINSFEUER", "BUEROKLAMMER", "SEGELBOOT", "UNIVERSITAET", "KOPF", "BEIN", "HAND", "FUSS", "FINGER", "DEUTSCHLAND", "SPORT", "BALL", "DRAHTLOS", "CHEF", "PFADFINDER", "FEUERMELDER", "LEHRER", "TAFEL", "KLASSENZIMMER", "STUHL", "TOILETTE", "TELEFONNUMMER", "AUTOHAENDLER", "WERKSTATT", "WASSER", "MINERALWASSER", "UHRZEIT", "TUER", "TUERKLINKE", "BUEGEL", "GESCHENK", "HANDTASCHE", "VENTILATOR", "STROMZAEHLER", "HEIZUNG", "RUECKEN", "RUECKENLEHNE", "ESSEN", "ABENDESSEN", "WEIHNACHTSESSEN", "SCHIEBETUER", "NEONROEHRE", "EDELGAS", "PERIODENSYSTEM", "ELEKTRON", "NEUTRON", "PROTON", "UMLAUFBAHN", "ENERGIE", "STOCKWERK", "FACHWERKHAUS", "MARKT", "VERKAEUFER", "KREUZWORTRAETSEL", "INTERNET", "TASSE", "HANDCREME", "HUND", "KUEHLSCHRANK", "TELLER", "GABEL", "MESSER", "UNTERTASSE", "BRETTCHEN", "KABELBINDER", "MEDIKAMENT", "LEITER", "FRAU", "MANN", "VIRUS", "SCHORNSTEIN", "DACH", "ZIEGELSTEIN", "ZIMT", "ZUCKER", "PFANNEKUCHEN", "CREPES", "MARMELADE", "KONFITUERE", "KAESE", "SCHINKEN", "WURST", "BUTTER", "NOTE", "MUSIK", "POSAUNE", "TROMPETE", "TUBA", "GARTEN", "STEIN", "KARNEVAL", "KOELN", "KOELSCH", "BUS", "TERMINIERUNG", "REIFEN", "REIFENDRUCK", "STROM", "FLUSS", "SEGEL", "RUDER", "RUDERBLATT", "BAUM", "MAST", "BACKBORD", "STEUERBORD", "GITTER", "GEFAENGNIS", "HAEFTLING", "FEUERWEHRAUTO", "POLIZEIAUTO", "REISE", "BAHN", "SCHIENE", "MODELLBAU", "FLUGZEUG", "BUNDESWEHR", "ZIVILDIENST", "FEIERABEND", "VORHAENGESCHLOSS", "BUCH", "STERNSCHNUPPE", "BOCKWURST", "AUTOPILOT", "TOLL", "HUSTENSIRUP", "SATZKONSTRUKTION", "ENSEMBLE", "WEINBERGSCHNECKE", "HYPERSCHALLGESCHWINDIGKEIT", "TEDDYBAER", "SEIDENPAPIER", "ZWISCHENSUMME", "HARRY", "LASSO", "WEIHNACHTSSTERN", "ZIMTSTERN", "SCHATTENBILD", "SCHADSTOFFBELASTUNG", "PIRATENSCHIFF", "POESIEALBUM", "TASCHENRECHNER", "PLATINBLOND", "STAMMBAUM", "SCHAFHERDE", "NUSSSTRUDEL", "MAMMUT", "BILDSCHIRM", "ZUHAUSE", "ZYSTE", "ZELLKERN", "FUSSPILZ", "NUMMERNSCHILD", "JAGDHUND", "MANO", "FLUCH", "FLITZEBOGEN", "LESELISTE", "FEUERBLITZ", "DOSIER", "FLASCHENHALS", "LESESTUNDE", "LESEBUCH", "STORCH", "KLAMOTTEN", "STIER", "ZWILLING", "JUNGE", "MAEDCHEN", "KAFFEETASSE", "MAUSOLEUM", "NASENBAER", "GIROKONTO"]
    main();
}

function main() {
    echoButtons();
    newWord();
}


function echoButtons() {
    i = 0;

    for (var letter = charCodeA; letter <= charCodeZ; letter++) {
        buttons[i] = document.createElement("button");
        buttons[i].innerHTML = String.fromCharCode(letter);

        buttons[i].addEventListener("click", function () {
            if (disableInput === false) {
                if (this.className.indexOf("disabled") == -1) {
                    processInput(this.innerHTML);
                    this.className = "disabled";
                }
            }
        });

        buttonContainer.appendChild(buttons[i]);
        i++;
    }
}

function newWord() {

    var element = document.getElementById("gameOver");
    element.style.display = 'none';

    selected = Math.floor(Math.random() * words.length); //0-641
    word = words[selected].split('');
    length = word.length;
    letterSpan = [];
    lives = 10;
    letterString = "";
    finished = true,
        disableInput = false;

    livesContainer.style.width = lives * 40 + "px";
    wordContainer.innerHTML = "";
    document.getElementsByTagName("html")[0].className = "";

    for (i = 0; i < length; i++) {
        letterSpan[i] = document.createElement("span");
        letterSpan[i].innerHTML = "_";
        wordContainer.appendChild(letterSpan[i]);
    }
    for (i = 0; i <= 25; i++){
        buttons[i].classList.remove('disabled');
    }
}

function processInput(character) {
    console.log(character)

    for (i = 0; i <= word.length - 1; i++) {
        //Code der überpüft ob der character im gesuchten Wort vorkommt
        if (character == word[i]) {
            hit = true;
            letterSpan[i].innerHTML = character;
        }

        if (letterSpan[i].innerHTML == "_") {
            finished = false;
        }
    }
    if (hit === true) {
        hit = false;

    } else {
        lives--;
        livesContainer.style.width = lives * 40 + "px";

        if (lives == 0) {
            gameOver();
        }
    }
    if (finished === true) {
        document.getElementsByTagName("html")[0].className = "finished";
        disableInput = true;
    } else {
        finished = true;
    }
}

function gameOver() {
    for (i = 0; i < length; i++) {
        if (letterSpan[i].innerHTML == "_") {
            letterSpan[i].innerHTML = word[i];
        }
    }
    var element = document.getElementById("gameOver");
    element.style.display = 'block';

    disableInput = true
    document.getElementsByTagName("html")[0].className = "gameOver";
}
